### ISSUE TITLE
For node.js add module.exports

### ISSUE THREAD

**Issue by nowshad-sust** [aishek/axios-rate-limit#3] opened 2019-06-19 05:35 UTC
So, the below code block doesn't work for nodejs apps, may be you targeted the frontend env.
```
exports.__esModule = true
exports.name = 'axiosRateLimit'
exports.default = axiosRateLimit
```

Adding one more line for the nodejs type will do the job:
```
module.exports = axiosRateLimit
```

**Comment by aishek** [comment] 2019-06-19 11:07
Oh, thank for the issue! I just published https://www.npmjs.com/package/axios-rate-limit/v/1.0.0 to fix it.

Could you confirm that the issue is fixed in version `1.0.0`?

**Closed by aishek** 2019-06-19 11:07 UTC

**Comment by nowshad-sust** [comment] 2019-06-19 13:01
@aishek thanks for the quick update 😃
